#!/bin/bash

export REGISTRY_HOST=ghcr.io
export USERNAME=getaux
export LAST_VERSION=1.0.8
export CONTAINER_NAME=api

cd $CONTAINER_NAME && \
docker build -t $CONTAINER_NAME . --no-cache && \
docker tag $CONTAINER_NAME $REGISTRY_HOST/$USERNAME/$CONTAINER_NAME:$LAST_VERSION && \
docker push $REGISTRY_HOST/$USERNAME/$CONTAINER_NAME:$LAST_VERSION && \
docker tag $CONTAINER_NAME $REGISTRY_HOST/$USERNAME/$CONTAINER_NAME:latest && \
docker push $REGISTRY_HOST/$USERNAME/$CONTAINER_NAME:latest